# Generated by Django 4.2.16 on 2024-10-26 15:04

from django.db import migrations, models


def fill_table(apps, schema_editor):
    Estoque = apps.get_model('hackathonApp', 'Estoque')

    sample_data = [
        Estoque(
            tecido=2200,
            algodao=2200,
            fio=2200,
            poliester=2200
        ),
    ]

    Estoque.objects.bulk_create(sample_data)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('tecido', models.IntegerField()),
                ('algodao', models.IntegerField()),
                ('fio', models.IntegerField()),
                ('poliester', models.IntegerField()),
            ],
        ),
        migrations.RunPython(fill_table),
    ]
